// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZBfXx_55culZqEMszF594eggarur0_Rg',
    appId: '1:865403137957:web:e8623328491e1dda86424c',
    messagingSenderId: '865403137957',
    projectId: 'myfirstapp-8c892',
    authDomain: 'myfirstapp-8c892.firebaseapp.com',
    storageBucket: 'myfirstapp-8c892.firebasestorage.app',
    measurementId: 'G-226LFREGVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOCoHdkKE_E5hWwwgm7N_UIzS2xUM0JkA',
    appId: '1:865403137957:android:48f44a4d78aaab2c86424c',
    messagingSenderId: '865403137957',
    projectId: 'myfirstapp-8c892',
    storageBucket: 'myfirstapp-8c892.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAso0_RXtMC3BYqZXSxD_Clt11un6quq_g',
    appId: '1:865403137957:ios:6233c48e3166889986424c',
    messagingSenderId: '865403137957',
    projectId: 'myfirstapp-8c892',
    storageBucket: 'myfirstapp-8c892.firebasestorage.app',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAso0_RXtMC3BYqZXSxD_Clt11un6quq_g',
    appId: '1:865403137957:ios:6233c48e3166889986424c',
    messagingSenderId: '865403137957',
    projectId: 'myfirstapp-8c892',
    storageBucket: 'myfirstapp-8c892.firebasestorage.app',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZBfXx_55culZqEMszF594eggarur0_Rg',
    appId: '1:865403137957:web:2fbc349ce6a55d2386424c',
    messagingSenderId: '865403137957',
    projectId: 'myfirstapp-8c892',
    authDomain: 'myfirstapp-8c892.firebaseapp.com',
    storageBucket: 'myfirstapp-8c892.firebasestorage.app',
    measurementId: 'G-EMZJ9FGKH7',
  );
}
